code_review
Ahn-seokjoo/Sfoide pull request #1
Opened 2021-10-04 12:21 UTC by Ahn-seokjoo

2021-10-04 12:52 UTC, sjjeong requested changes

2021-10-04 12:52 UTC, sjjeong commented on app/src/main/java/com/example/sfoide/ui/userlist/MainActivity.kt
> +        val swipe = findViewById<SwipeRefreshLayout>(R.id.swipeLayout)
UserDetailActivity와 동일하게 ViewBinding 적용해주세요

2021-10-04 12:52 UTC, sjjeong commented on app/src/main/java/com/example/sfoide/ui/userlist/MainActivity.kt
> +        initScrollListener(result)
불필요한 파라미터를 전달하지 않고 해결해보세요

2021-10-04 12:52 UTC, sjjeong commented on app/src/main/java/com/example/sfoide/ui/userlist/MainActivity.kt
> +        lifecycleScope.launch {
lifecycleScope.launch는 필요없어 보이네요

2021-10-04 12:52 UTC, sjjeong commented on app/src/main/java/com/example/sfoide/ui/userlist/MainActivity.kt
> +                adapter.submitList(response.body()!!.results)
데이터가 추가 되는게 아니라 덮어씌워지네요

2021-10-04 12:52 UTC, sjjeong commented on app/src/main/java/com/example/sfoide/ui/userlist/MainActivity.kt
> +            swipe.isRefreshing = false // 새로 고침 아이콘 제거
swipe에 refresh 아이콘이 유저입장에서 로딩을 보여주는 indicator역할을 하기 때문에
실제 네트워크 요청이 시작되면 true, 네트워크 요청이 끝나면 false로 하도록 해주세요

2021-10-04 12:52 UTC, sjjeong commented on app/src/main/java/com/example/sfoide/ui/userlist/UserViewHolder.kt
> +class UserViewHolder(private val binding: UserItemBinding, onItemClick: (UserData.Result) -> Unit) : RecyclerView.ViewHolder(binding.root) {
UserItemBinding객체를 외부에서 받지 말고 안에서 생성해보세요

2021-10-04 12:52 UTC, sjjeong commented on app/src/main/java/com/example/sfoide/ui/userlist/RecyclerViewAdapter.kt
> +class RecyclerViewAdapter(
클래스 이름 변경해주세요.
이름만 보고서 어떤 어뎁터인지 유추하기 어렵습니다.

2021-10-04 12:52 UTC, sjjeong commented on app/src/main/java/com/example/sfoide/ui/userdetail/UserDetailActivity.kt
> +                    gender + country
하나의 String template으로 처리해보세요

2021-10-04 12:52 UTC, sjjeong commented on app/src/main/java/com/example/sfoide/ui/userdetail/UserDetailActivity.kt
> +    private fun initIntent(item: UserData.Result?) {
실제 내부에서 하는 동작이 View에 ClickListener추가하는 건데 함수명만 보고 유추하기 어렵습니다
적절한 함수명으로 변경해보세요

2021-10-04 12:52 UTC, sjjeong commented on app/src/main/res/layout/activity_main.xml
> +            android:padding="10dp"
4의 배수나 8의 배수로 해주는게 좋습니다

2021-10-04 12:52 UTC, sjjeong commented on app/src/main/res/layout/activity_user_detail.xml
> +        </LinearLayout>
불필요해보이는 LinearLayout이네요
비슷한 부분도 전부 제거해주세요

2021-10-04 12:52 UTC, sjjeong commented on app/src/main/res/layout/user_detail.xml
> +<?xml version="1.0" encoding="utf-8"?>
이 파일은 안쓰는거니까 제거해주세요

2021-10-04 12:52 UTC, sjjeong commented on app/src/main/res/layout/user_item.xml
> +        android:layout_width="match_parent"
파일명을 item_user로 변경해주세요

2021-10-05 16:58 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/sfoide/ui/userlist/MainActivity.kt
> +        lifecycleScope.launch {
5d80e2487e5e1f7d6bcb3c51c20afce987e21c80

2021-10-05 16:58 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/sfoide/ui/userlist/MainActivity.kt
> +        lifecycleScope.launch {
5d80e2487e5e1f7d6bcb3c51c20afce987e21c80 
라이프 사이클 스코프 제거했습니다.

2021-10-05 16:59 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/sfoide/ui/userdetail/UserDetailActivity.kt
> +                    gender + country
8c9ede17af7100c4df5ab665b187fb421486e49e 하나의 String Template로 수정했습니다.

2021-10-05 16:59 UTC, Ahn-seokjoo commented on app/src/main/res/layout/user_detail.xml
> +<?xml version="1.0" encoding="utf-8"?>
f293d28139c8fcb3afd53e6584486dd30abf3b0e 사용하지 않는 XML 제거했습니다.

2021-10-05 16:59 UTC, Ahn-seokjoo commented on app/src/main/res/layout/user_item.xml
> +        android:layout_width="match_parent"
311f4e1491208e9b9111bd7a6d5277752cd750a3 파일명 리네이밍 했습니다.

2021-10-05 16:59 UTC, Ahn-seokjoo commented on app/src/main/res/layout/activity_user_detail.xml
> +        </LinearLayout>
95dfb8b309013b06e205b7ad5c3ad5c7ef7fbd0e 불필요한 뷰그룹 모두 삭제했습니다.

2021-10-05 17:00 UTC, Ahn-seokjoo commented on app/src/main/res/layout/activity_main.xml
> +            android:padding="10dp"
df8cfed9dfa7a762cd72bc250ab0470967fc7a62 padding 값 모두 교체했습니다. 
그런데 paddingStart의 경우 꼭 paddingEnd도 지정해주어야 하나요??? IDE에서 권장사항으로 뜹니다.

2021-10-05 17:01 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/sfoide/ui/userlist/RecyclerViewAdapter.kt
> +class RecyclerViewAdapter(
d7a725431a1db31f4e926039fafdf0beb011da3f 클래스 이름 변경했습니다. 그런데 좀 길다고 생각됩니다.

2021-10-05 17:07 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/sfoide/ui/userlist/MainActivity.kt
> +        val swipe = findViewById<SwipeRefreshLayout>(R.id.swipeLayout)
9156656eec5192285c704d075c7dce34bc34a7b8 MainActivity에도 ViewBinding 적용했습니다.

2021-10-05 17:12 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/sfoide/ui/userdetail/UserDetailActivity.kt
> +    private fun initIntent(item: UserData.Result?) {
318774cefb3dd93a5216de2b3b45570f2626b1c8 함수명 변경했습니다.

2021-10-07 09:20 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/sfoide/ui/userlist/MainActivity.kt
> +        initScrollListener(result)
edb701ba2413b8130ddca1c403244796d05c3b89 파라미터 모두 제거할 수 있도록 했습니다.

2021-10-09 11:01 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/sfoide/ui/userlist/MainActivity.kt
> +                adapter.submitList(response.body()!!.results)
2c6f55ec599dbf91b0b129afcda77b7bbbd2ce49 페이징으로 구현했습니다.

2021-10-09 16:13 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/sfoide/ui/userlist/MainActivity.kt
> +            swipe.isRefreshing = false // 새로 고침 아이콘 제거
2590cbb87dfce05ceacc0049f7a10703b93037ea 해결했습니다.

2021-10-10 12:43 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/sfoide/ui/userlist/UserViewHolder.kt
> +class UserViewHolder(private val binding: UserItemBinding, onItemClick: (UserData.Result) -> Unit) : RecyclerView.ViewHolder(binding.root) {
250da540090cc03951fae918bff6efa36d2d4c06 해결했습니다.

2021-10-11 05:28 UTC, sjjeong commented on app/src/main/java/com/example/sfoide/ui/userlist/RecyclerViewAdapter.kt
> +class RecyclerViewAdapter(
UserAdapter 정도면 돼요

2021-10-11 05:29 UTC, sjjeong commented on app/src/main/res/layout/activity_main.xml
> +            android:padding="10dp"
꼭 지정해줄 필요는 없습니다

2021-10-11 05:30 UTC, sjjeong approved these changes

2021-10-11 05:47 UTC, merged